name: Build and push Docker images

on:
  workflow_dispatch:
  schedule:
  - cron: '16 11 * * *'

env:
  TZ: Asia/Shanghai 
  LSKYPRO_VER: 2.0.4

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download and Unzip Upstream Source Code
        run: |
          curl -OL https://github.com/lsky-org/lsky-pro/archive/refs/heads/master.zip
          unzip *.zip
          mv ./lsky-pro-master/* ./
          mv ./lsky-pro-master/.env.example ./
          rm -rf master.zip lsky-pro-master

      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
        
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
      - name: Install Dependencies
        run: composer install

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push
        # run: |
          # docker build -t coldpig/lskypro-docker:latest .
          # docker push coldpig/lskypro-docker:latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: coldpig/lskypro-docker:v_${{ env.LSKYPRO_VER }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: coldpig/lskypro-docker
          short-description: ☁️ 兰空图床 (Lsky Pro) - ☁ Your photo album on the cloud.  新版 ${{ env.LSKYPRO_VER }}，第三方维护的 Docker 镜像，会每天拉取一次源仓库源码构建镜像。
          readme-filepath: ./README.md

      - name: Create Version Latest
        run: |
          docker buildx imagetools create -t coldpig/lskypro-docker:latest \
            coldpig/lskypro-docker:v_${{ env.LSKYPRO_VER }}
      

        
        
        
          
